SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE TO_DATE(START_DATE, 'YYYY-MM-DD') BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
                        OR TO_DATE(END_DATE, 'YYYY-MM-DD') BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
                        OR (TO_DATE(START_DATE, 'YYYY-MM-DD') <= TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE(END_DATE, 'YYYY-MM-DD') >= TO_DATE('2022-11-30', 'YYYY-MM-DD')))
AND DURATION_TYPE = '30일 이상'
AND ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;

---
SELECT DISTINCT(A.CAR_ID), A.CAR_TYPE, A.DAILY_FEE*(1-(C.DISCOUNT_RATE/100))*30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID=B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_ID NOT IN (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(END_DATE,'YYYY-MM-DD') BETWEEN '2022-11-01' AND '2022-11-30'
OR TO_CHAR(START_DATE,'YYYY-MM-DD') BETWEEN '2022-11-01' AND '2022-11-30'
OR TO_CHAR(END_DATE,'YYYY-MM-DD')>'2022-11-01')
AND C.DURATION_TYPE='30일 이상'
AND A.CAR_TYPE IN ('세단','SUV')
AND A.DAILY_FEE*(1-(C.DISCOUNT_RATE/100))*30 BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
