--진료과별 총 예약 횟수 출력하기 
SELECT MCDP_CD, COUNT(APNT_NO) 
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD,'YYYYMM')='202205'
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD

-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(*)
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
OR OPTIONS LIKE '%열선시트%'
OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE

-- 동명 동물 수 찾기
--COUNT(*)하면 틀림 !
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME)>=2
ORDER BY NAME


-- 입양 시각 구하기(1)
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR , COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME,'HH24'))>8
AND TO_NUMBER(TO_CHAR(DATETIME,'HH24'))<20
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
ORDER BY HOUR
