-- 가격이 제일 비싼 식품의 정보 출력하기.sql(Lv.2)
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT)

-- 최댓값 구하기.sql (Lv.1)
SELECT MAX(DATETIME)
FROM ANIMAL_INS

-- 최솟값 구하기.sql (Lv.2)
SELECT MIN(DATETIME) 
FROM ANIMAL_INS

-- 동물 수 구하기.sql (Lv.2)
SELECT COUNT(ANIMAL_ID)
FROM ANIMAL_INS

-- 중복 제거하기.sql (Lv.2)
SELECT COUNT(DISTINCT(NAME))
FROM ANIMAL_INS

-- 가장 비싼 상품 구하기.sql (Lv.1)
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT