SELECT C.USER_ID, C.NICKNAME, C.TOTAL_SALES
FROM(
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID=B.USER_ID 
WHERE STATUS='DONE'
GROUP BY B.USER_ID, B.NICKNAME
    )C
WHERE C.TOTAL_SALES>=700000
ORDER BY TOTAL_SALES


"""
가능한 방법 2
"""
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER A
JOIN
(
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS='DONE'
GROUP BY WRITER_ID
    )B ON A.USER_ID=B.WRITER_ID
WHERE B.TOTAL_SALES>=700000
ORDER BY B.TOTAL_SALES